### ISSUE TITLE
License

### ISSUE THREAD

**Issue by snh** [biemster/rpi4_alpine_netboot#4]
I noticed that there doesn't appear to be a license clearly defined for this incredibly handy script.

For those who'd like to use, incorporate, and/or contribute back to the great work that has been done here, it'd be a big help if this was available under an open source license.

GitHub have some [documentation available](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) that guides you through adding a license to an existing repository if this is something you are interested in doing.

Thank you for all your great work here @biemster with this script, @erincandescent for https://gist.github.com/erincandescent/c3266fc3cbb7fe21be0ab1def7adbc48 and `sodface` on the Alpine wiki for https://wiki.alpinelinux.org/wiki/Raspberry_Pi_-_Headless_Installation.

**Comment by theAkito** [comment]
While I totally can understand the concern with real libraries and similar projects, I can not follow the same argumentation for a project like this. While the script is pretty handy and useful, it's after all still just a bunch of CLI actions written into a script. Not even sure if things like this can be licensed, because anyone could create a similar script, simply because there are only very limited ways to achieve the same goal. So, theoretically, even if this script were proprietary, people still would be allowed to write a very similar script, as they do not have much freedom in achieving the result this script is aiming at. 🙂

**Comment by biemster** [comment]
I was under the impression that code without a clear license on GitHub is automatically licensed quite permissively, and since all that legal stuff takes out all the fun of project like these I'll license it under the Biemster licence:
1) Use it however you see fit.
2) Go back to 1)

@snh I'm not trying to be rude, thanks for your interest and appreciation of the script! :+1:

**Comment by snh** [comment]
@biemster Not a problem at all, I appreciate your response and clarity on your intentions for the script. 🙇 

Thank you again for putting it together! It is very useful.

**Comment by biemster** [comment]
You're welcome! I'm still actively using it currently, so please don't hesitate to report issues or improvements and I'll implement them if possible.
I'm planning for example to add the generation of my nginx reverse proxy with caching config to the script, since my setup uses that now very satisfactory to keep all the default packages served on the local network.
Also I recently fixed an issue after weeks of trial and error where the built-in ethernet is not used during boot when an usb-ethernet adapter is attached.
